### PR TITLE
Add FindCbc.cmake

### PR DESCRIPTION
**Pull request by tomas2211**
Adding `FindCbc.cmake` that finds all libraries related to solving ILP.

### CODE REVIEW

**Review by matyas-hollmann — COMMENTED** [review]
I would suggest capitalizing all CMAKE variables, it's a common practice. Thanks.

**Comment by zap150** [comment]
> 

What do you mean by capitalisation? E.g. `Cbc_LIBRARIES`? I believe it has to be like this due to our build system if the library file is `libCbc.so`. Am I mistaken? Our build system takes `Cbc`, appends it by `_FOUND`, checks for the variable and then adds `-lCbc`.

**Comment by tomas2211** [comment]
I tried it. Capitalizing variables seems to require capital `CBC` in `define_module()`. That's a bit confusing as the library is actually called `Cbc` (https://github.com/coin-or/Cbc).

**Comment by vaclavblazek** [comment]
Maybe using `pkg-config` would be better (package maintainers know better where stuff is and how to link it). See `Modules/FindSqlite3.cmake` as a reference.

**Comment by tomas2211** [comment]
Thanks, `pkg-config` seems to find all libraries in coin-or that are required to use `cbc` so now there is no need to list all of them (Osi, CoinUtils, Cgl, ...).

**Review by zap150 — APPROVED** [review]

**Pull request merged**
